//https://codebeautify.org/xmltojson
export let mockresponse = {
	"whiskyregistry": {
		"distilleries": {
			"distillery": [
				{
					"code": "Ardbeg",
					"shortname": "Ardbeg",
					"description": "The distillery Ardbeg has arisen from an illegal distillery which has been in production since 1794. Ardbeg has been officially founded by John McDougall 1815. The distillery is located at the south side of Islay in the neighbourhood of Port Ellen, Lagavulin and Laphroaig. \nArdbeg has been closed from 1981 to 1989 and from 1996 to 1997. Especially the eight years in the 80s have a very negative influence to the Ardbeg products nowadays. Because of the interruption in the production, there are no casks from the eighties available. These vintage bottlings are missing in product palette. \nAs can be notified throughout a lot of distilleries, there is a wide range of bottlings without an age notice. This gives the distilleries a chance to mix older casks with pretty new ones. Ardbeg is one of the distilleries which drives this way of marketing to the top. All bottlings in last years have come out without an age declaration.\nArdbeg is furthermore one of the distilleries with a very aggressive marketing. Every year comes a new bottling to the market and there is a lot of commercials and advertising for that. The release of the new bottling is celebrated at the so called ,Ardbeg Day‘.",
					"location": "PA42 7EA Port Ellen, Islay, Scotland",
					"latlong": "55.6404353,-6.1083340000000135"
				},
				{
					"code": "Arran",
					"shortname": "Arran",
					"description": "The distillery Arran, located near the city of Lochranza on the Isle of Arran, is the first new distillery on that island since 150 years. it has been opened in 1991. The first bottles have been sold since 2001. In the past, there have been more than 50 distilleries on Arran, but most of then have been illegal and produced the whisky only for the private consume.\nThere is a wide range of bottlings of Arran whisky on the market. A lot of them got finishes in a wide variety of different cask types.\nArran is a small scale distillery and was designed from the outset to be aesthetically pleasing with mock pagodas and whitewashed buildings which blend in well with the island's older architecture.\nPronounced -arr-en; meaning Place of peaked hills.\nOfficially opened on August 17th.\nThey received the barley already malted and grinded.\nFirst in 2007 a malt mill was installed.\nNo production 2002-04.\nHas a stainless steel semi-lauter mash tun, with a copper dome.\nFive washbacks made of Oregon pine.\nTwo indirect fired pot stills.\nShell and tube condensers. \nBetween October 2016 and January 2017 2 additional stills have been put in place to a new total of 4 stills.",
					"location": "A841 KA27 8HJ Lochranza, Arran, Argyll, Scotland  Islands",
					"latlong": "55.5806165,-5.210857300000043"
				},
				{
					"code": "Bowmore",
					"shortname": "Bowmore",
					"description": "Bowmore is one of only a handful of Scottish distilleries which still operates it's own floor maltings, with three currently in use. They provide up to 40 per cent of the distillery's malt requirements.\nBowmore is proud of it's environmental record, and in 1990 a warehouse was donated to the local community for conversion into a swimming pool. It is heated by hot water from the stillroom's condensers.\nPronounced bow-MORE Meaning The big bend/curve\nExpands 1837-51. Closed 1929 and during WWII. Rebuilt, renovated and the two pair of pot stills gets Steam-heated in 1963. Their floor-malting (three floors) covers about a third of the needs. They switched back to wooden wash backs in 1990 because the felt that the stainless one affected the taste. When were they stainless installed? A stainless steel semi-lauter mash tun. The own malting covers about 30-40% of the needs. The rest from Simpsons are mixed together.",
					"location": "School Street, PA43 7GS Bowmore, Isle of Islay, Argyll, Scotland  Islay",
					"latlong": "55.756868,-6.289846099999977"
				},
				{
					"code": "Bruichladdich",
					"shortname": "Bruichladdich",
					"description": "Pronounced Brew-ich-laddie. Since the Second World War, Bruichladdich has been a minimally peated Islay malt. Now batches of heavily peated spirit are also distilled, namely Port Charlotte, peated to 40 ppm, and Octomore the most heavily peated whisky in the world, peated to at least 80 ppm. Barley is exclusively Scottish grown, and is produced on 23 farms. Almost half is cultivated on Islay and the rest is organically grown on the mainland.\n\nClosed 1929-36. Floor-malting ends 1961. Expands from one to two pair of pot stills 1975. In the early 1980's it only operated one day per week. Mothballed 1983. In production a few months 1998. Opens again 2001-05-29. 2011 a Lomond still from Inverleven were installed. Only been used for making gin so far. Have its own bottling line. Uses a cast iron, open mash tun from 1881.",
					"location": "Islay, Argyll , PA49 7VN, Scotland, Islay",
					"latlong": "42.1097474,-88.0459674"
				},
				{
					"code": "Bunnahabhain",
					"shortname": "Bunnahabhain",
					"description": "Pronounced Boon-a-havun, this distillery, although it may not seem obvious at first glance was constructed in the style of a Bordeaux watchtower or castel.\nSince 2003 quantities of more heavily peated spirit have been distilled annually at Bunnahabhain for blending purposes and a single malt bottling.\nTo edit in if wanted:\nIn the early 1960's they started to use another water source. Expands from one to two pair of pot stills 1963 and the floor-malting ends (three floors). Closed 1982-84. Closed Oct 2002-Jan 2003.\nSince late 1990's they make some (20%?) peated spirit annually.\nbasbear",
					"location": "Port Askaig, Islay, PA46 7RP, Scotland, Islay",
					"latlong": "55.883335,-6.130126000000018"
				},
				{
					"code": "CaolIla",
					"shortname": "Caol Ila",
					"description": "Caol Ila is een distilleerderij nabij Port Askaig op het eiland Islay, Schotland. De distilleerderij is beroemd om het gelijknamige merk single malt Scotch whisky",
					"location": "Port Askaig, Isle of Islay PA46 7RL, Verenigd Koninkrijk",
					"latlong": "55.854030, -6.108570"
				},
				{
					"code": "Cooley",
					"shortname": "Cooley Distillery",
					"description": "De Cooley Distillery is de enige onafhankelijke distilleerderij in Ierland en ligt op Cooley Peninsula in County Louth aan de Ierse oostkust. De distilleerderij is opgericht in 1987 door John Teeling die het verval van de Ierse whiskey zag en op deze manier een mogelijkheid had om hier wat tegen te doen.",
					"location": "County Louth, Ierland",
					"latlong": "53.716770, -6.354350"
				},
				{
					"code": "UsHeit",
					"shortname": "Us Heit Distillery",
					"description": "Frysk Hynder is de eerste single malt van Nederlandse bodem en ontstond als liefhebberij van de bierbrouwers van Us Heit, Aart en Marianne van der Linde. De whisky is voor het eerst gestookt en gelagerd in 2002, de eerste flessen Frysk Hynder kwamen in 2005 op de markt.\nDe whisky wordt gedistilleerd uit een speciaal bier, welke gebrouwen is uit gerookt mout. Na het tweevoudige destillatieproces (waarbij het alcoholpercentage naar 40% gaat) wordt de whisky 3 jaar gelagerd (gerijpt) op eikenhouten vaten, wat voor een single malt whisky het minimum is. De vaten zijn afkomstig van wijnboeren uit Frankrijk en Portugal. De whisky wordt gebotteld volgens het un-chillfiltered principe (zonder diepkoeling en filtratie), waardoor deze bij koud serveren wat troebel kan lijken. De jaarproductie bedraagt 10.000 liter of 14.000 flessen (gemiddeld 77 flessen per dag); elke fles Frysk Hynder heeft etiket, waarop met de hand de kenmerken van de batch (de partij flessen die uit hetzelfde vat van 600 liter gebotteld zijn) ingevuld zijn.[2]",
					"location": "Snekerstraat 43, 8701 XC Bolsward",
					"latlong": "53.060870, 5.534190"
				},
				{
					"code": "Glenfiddich",
					"shortname": "Glenfiddich",
					"description": "Glenfiddich is een Speyside single malt Scotch whisky, die door William Grant & Sons in de Glenfiddich Distillery in Dufftown wordt gedistilleerd. Glenfiddich wordt uitgesproken met een harde g-klank aan het einde.",
					"location": "Dufftown, Keith AB55 4DH, Verenigd Koninkrijk",
					"latlong": "57.454159, -3.127790"
				},
				{
					"code": "Glengoyne",
					"shortname": "Glengoyne",
					"description": "",
					"location": "Dumgoyne, Killearn, Glasgow G63 9LB, Verenigd Koninkrijk",
					"latlong": "56.016150, -4.357780"
				},
				{
					"code": "Glenlivet",
					"shortname": "Glenlivet",
					"description": "The Glenlivet is een Speyside single malt whisky, geproduceerd in de The Glenlivet Distillery in Ballindalloch tussen Tomintoul en Dufftown, Gelegen in het graafschap Banffshire, Schotland.",
					"location": "Castleton Of Blairfindy, Glenlivet AB37 9DB, Verenigd Koninkrijk",
					"latlong": "57.342520, -3.339220"
				},
				{
					"code": "Jura",
					"shortname": "Isle of Jura",
					"description": "Isle of Jura Single Malt is een Schotse single malt whisky, die op het eiland Jura wordt geproduceerd. Isle of Jura is een opvallend milde en droge whisky, met een lichte turfsmaak, en een tintje Acaciahoning. De whisky is er in een 10, 16 en 21 jaar oude botteling.",
					"location": "Craighouse, Isle of Jura PA60 7XT, Verenigd Koninkrijk",
					"latlong": "55.833550, -5.954070"
				},
				{
					"code": "Kilchoman",
					"shortname": "Kilchoman",
					"description": "Kilchoman is een Schotse whiskydistilleerderij, in juni 2005 gestart met de productie. Het is de eerste nieuwe distilleerderij op het eiland Islay van de afgelopen 124 jaar. Het gehele proces, vanaf het verbouwen van de gerst tot aan het bottelen vindt plaats op Rockside Farm, aan de noordwestkant van het eiland.",
					"location": "Rockside Farm, Bruichladdich, Isle of Islay PA49 7UT, Verenigd Koninkrijk",
					"latlong": "55.801830, -6.407190"
				},
				{
					"code": "Lagavulin",
					"shortname": "Lagavulin",
					"description": "Lagavulin Single Malt is een Schotse Islay single malt whisky, die in het dorp Port Ellen wordt gedistilleerd. Deze single malt whisky vertegenwoordigt de Islay single malts in de Classic Malts of Scotland-serie van Diageo. Op de plaats waar nu de Lagavulin distilleerderij staat wordt vanaf 1742 al whisky gemaakt.",
					"location": "Distillery Cottages, Lagavulin, Isle of Islay PA42 7DZ, Verenigd Koninkrijk",
					"latlong": "55.635800, -6.126810"
				},
				{
					"code": "Laphroaig",
					"shortname": "Laphroaig",
					"description": "De Laphroaig distilleerderij werd in 1815[1] door de broers Alex en Donald Johnston opgericht. De Johnston broers waren in feite McDonalds, die na de mislukte Jacobitische opstand hun naam wijzigden, en neerstreken op het eiland Islay. Hun afstammelingen bestuurden de distilleerderij tot 1954. Toen Ian Hunter kinderloos stierf in 1954, liet hij de distilleerderij na aan een van zijn managers, Bessie Williamson. De distilleerderij werd verkocht aan Long John International in de jaren zestig, en vervolgens aan Allied Domecq. Allied Domecq werd op zijn beurt weer door Fortune Brands aangekocht in 2005.\nLaphroaig is een whisky met een sterke, uitgesproken smaak. Ze wordt meestal verkocht als 10 years old, maar ook de 18 years old is populair. De 15 years old is al enige tijd van de markt, maar onder Laphroaig-kenners zeer geliefd. Daarnaast zijn er nog varianten van 30 en 40 jaar oud, maar deze treft men slechts zelden aan. Een druppel water in de whisky legt volgens sommige drinkers een goede nadruk op het turfachtige aroma.\nLaphroaig experimenteert om de smaak van historische whisky’s terug te krijgen. Een kleiner vat (de Laphroaig Quarter Cask) is recentelijk in gebruik genomen, waarmee men hoopt de smaak van whisky zoals die honderd jaar geleden was, terug te vinden. In 1994 kreeg Laphroaigh een Koninklijke goedkeuring van ZKH Prins Charles, die persoonlijk door de prins werd uitgereikt.",
					"location": "Port Ellen, Isle of Islay PA42 7DU, Verenigd Koninkrijk",
					"latlong": "55.632130, -6.186290"
				},
				{
					"code": "Macallan",
					"shortname": "Macallan",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "Oban",
					"shortname": "Oban",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "PortEllen",
					"shortname": "Port Ellen",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "Scapa",
					"shortname": "Scapa",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "Springbank",
					"shortname": "Springbank",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "Talisker",
					"shortname": "Talisker",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "Tobermory",
					"shortname": "Tobermory",
					"description": "",
					"location": "",
					"latlong": ""
				},
				{
					"code": "Wambrechies",
					"shortname": "Distillerie Claeyssens de Wambrechies",
					"description": "",
					"location": "",
					"latlong": ""
				}
			]
		},
		"bottlings": {
			"bottling": [
				{
					"code": "Ardbeg Ten",
					"shortname": "Ardbeg Ten",
					"region": "Islay",
					"description": "Category: Single Malt \nBottled: -\nStated age: 10 years old \nCasktype: Bourbon Barrel \nStrength: 46.0 % Vol. \nSize: 700 ml",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "Bourbon Barrel",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010494195286"
				},
				{
					"code": "Ardbeg 10 and 17 Year Old Presentation Tin",
					"shortname": "Ardbeg 10 and 17 Year Old Presentation Tin",
					"region": "Islay",
					"description": "",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10, 17 years old",
					"casktype": "",
					"strength": "",
					"size": "",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010494189421"
				},
				{
					"code": "Ardbeg 17-year-old",
					"shortname": "Ardbeg 17-year-old",
					"region": "Islay",
					"description": "Category: Single Malt\nBottled: 1997\nStated age: 17 years old\nCasktype: Bourbon Barrel\nStrength: 40.0 % Vol.\nSize: 700 ml",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "17 years old",
					"casktype": "Bourbon Barrel",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "0.05",
					"barcode": "5010494190281"
				},
				{
					"code": "Ardbeg 18-year-old",
					"shortname": "Ardbeg 18-year-old",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nArdbeg\nBottler\nDouglas Laing (DL)\nBottling serie\nOld Malt Cask\nVintage\n03.1991\nBottled\n04.2009\nStated Age\n18 years old\nCasktype\nRefill Hogshead\nCasknumber\nDL 5120\nNumber of bottles\n357\nStrength\n50.0 % Vol.\nSize\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Douglas Laing (DL)",
					"brandcodes": "",
					"statedage": "18 years old",
					"casktype": "Refill Hogshead",
					"strength": "50.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5014218773958"
				},
				{
					"code": "Ardbeg Alligator",
					"shortname": "Ardbeg Alligator",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nArdbeg\nBottler\nDistillery Bottling\nBottled\n2011\nCasktype\nNew American White Oak\nStrength\n51.2 % Vol.\nSize\n50 ml 700 ml 700 ml 750 ml\nBottle code\nL11 195\nBarcode\n5010494904185",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "New American White Oak",
					"strength": "51.2 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "0.5",
					"barcode": "5010494904185"
				},
				{
					"code": "Ardbeg Blasda",
					"shortname": "Ardbeg Blasda",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nArdbeg\nBottler\nDistillery Bottling\nBottling serie\nLimited Edition\nBottled\n2008\nCasktype\nSherry Hogshead\nNumber of bottles\n18000\nStrength\n40.0 % Vol.\nSize\n50 ml 700 ml\nBottle code\nL8 225 1745 6ML\nBarcode\n5010494252286",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Sherry Hogshead",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "0.5",
					"barcode": "5010494252286"
				},
				{
					"code": "Ardbeg Corryvreckan",
					"shortname": "Ardbeg Corryvreckan",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nArdbeg\nBottler\nDistillery Bottling\nBottled\n06.10.2015\nStrength\n57.1 % Vol.\nSize\n700 ml\nBottle code\nL63645\nBarcode\n5010494296280",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "57.1 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010494296280"
				},
				{
					"code": "Ardbeg Dark Cove",
					"shortname": "Ardbeg Dark Cove",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nArdbeg\nBottler\nDistillery Bottling\nBottled\n11.02.2016\nCasktype\nDark Sherry Casks\nStrength\n46.5 % Vol.\nSize\n700 ml 700 ml 700 ml 750 ml\nBottle code\nL64711\nBarcode\n5010494931969",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Dark Sherry Casks",
					"strength": "46.5 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "0.5",
					"barcode": "5010494931969"
				},
				{
					"code": "Ardbeg Renaissance",
					"shortname": "Ardbeg Renaissance",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nArdbeg\nBottler\nDistillery Bottling\nVintage\n1998\nBottled\n2008\nStated Age\n10 years old\nNumber of bottles\n21000\nStrength\n55.9 % Vol.\nSize\n700 ml\nBottle code\nL8 121\nBarcode\n5010494294286",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "55.9 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "0.5",
					"barcode": "5010494294286"
				},
				{
					"code": "Ardbeg Uigeadail",
					"shortname": "Ardbeg Uigeadail",
					"region": "Islay",
					"description": "Category: Single Malt  \nBottled: - \nStated age: - \nCasktype: Bourbon / Sherry Casks  \nStrength: 54.2 % Vol.  \nSize: 700 ml",
					"category": "Single Malt",
					"distillerycodes": "Ardbeg",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Bourbon / Sherry Casks",
					"strength": "54.2 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "0.5",
					"barcode": "5010494220278"
				},
				{
					"code": "Arran 10-year-old",
					"shortname": "Arran 10-year-old",
					"region": "Island",
					"description": "Category\nSingle Malt\nDistillery\nArran\nBottler\nDistillery Bottling\nBottled\n02.2006\nStated Age\n10 years old\nStrength\n46.0 % Vol.\nSize\n700 ml\nLabel\nHouse Label\nBarcode\n5060044480638",
					"category": "Single Malt",
					"distillerycodes": "Arran",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5060044480638"
				},
				{
					"code": "Bowmore No. 1",
					"shortname": "Bowmore No. 1",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLED\n2017\nCASKTYPE\nFirst Fill Bourbon Casks\nSTRENGTH\n40.0 % Vol.\nSIZE\n700 ml\nLABEL\nOur No. 1 Malt\nBARCODE\n5010496004494",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "First Fill Bourbon Casks",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496004494"
				},
				{
					"code": "Bowmore Legend",
					"shortname": "Bowmore Legend",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLED\n2004\nSTRENGTH\n40.0 % Vol.\nSIZE\n700 ml 750 ml\nLABEL\nwhite stripe on capsule\nBARCODE\n5010496010815",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010496010815"
				},
				{
					"code": "Bowmore Black Rock",
					"shortname": "Bowmore Black Rock",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nBowmore\nBottler\nDistillery Bottling\nBottled\n2015\nCasktype\nPredominately Ex-Spanish Sherry Casks\nStrength\n40.0 % Vol.\nSize\n1000 ml\nBottle code\nL152373\nBarcode\n5010496003824\nBottled for\nTravel Retail Exclusive",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Predominately Ex-Spanish Sherry Casks",
					"strength": "40.0 % Vol.",
					"size": "1000 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496003824"
				},
				{
					"code": "Bowmore Gold Reef",
					"shortname": "Bowmore Gold Reef",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nBowmore\nBottler\nDistillery Bottling\nBottled\n04.2014\nCasktype\nBourbon & Sherry Cask from America & Europe\nStrength\n43.0 % Vol.\nSize\n1000 ml\nBarcode\n5010496003831",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Bourbon & Sherry Cask from America & Europe",
					"strength": "43.0 % Vol.",
					"size": "1000 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496003831"
				},
				{
					"code": "Bowmore 08-year-old",
					"shortname": "Bowmore 08-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLED\n2000\nSTATED AGE\n08 years old\nSTRENGTH\n40.0 % Vol.\nSIZE\n700 ml\nLABEL\nwhite stripe on capsule\nBOTTLE CODE\nL0 157\nBARCODE\n5010496060810",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "08 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010496060810"
				},
				{
					"code": "Bowmore 09-year-old",
					"shortname": "Bowmore 09-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLING SERIE\nSherry Cask Matured\nSTATED AGE\n09 years old\nCASKTYPE\nOloroso Sherry and Bourbon Casks\nSTRENGTH\n40.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "09 years old",
					"casktype": "Oloroso Sherry and Bourbon Casks",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496004432"
				},
				{
					"code": "Bowmore 12-year-old",
					"shortname": "Bowmore 12-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nSTATED AGE\n12 years old\nSTRENGTH\n40.0 % Vol.\nSIZE\n350 ml",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "12 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "350 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496081013"
				},
				{
					"code": "Bowmore 15-year-old",
					"shortname": "Bowmore 15-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLED\n2017\nSTATED AGE\n15 years old\nCASKTYPE\nSherry Cask Finish\nSTRENGTH\n43.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "15 years old",
					"casktype": "Sherry Cask Finish",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010496020821"
				},
				{
					"code": "Bowmore 17-year-old Whitesands",
					"shortname": "Bowmore 17-year-old Whitesands",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nBowmore\nBottler\nDistillery Bottling\nBottling serie\nWhite Sands\nStated Age\n17 years old\nCasktype\nEx-Bourbon Casks\nStrength\n43.0 % Vol.\nSize\n700 ml\nBarcode\n5010496003848\nBottled for\nTravel Retail Exclusive\nAdded on\n14 Jun 2015 7:15 pm",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "17 years old",
					"casktype": "Ex-Bourbon Casks",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496003848"
				},
				{
					"code": "Bowmore 18-year-old",
					"shortname": "Bowmore 18-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLED\n2017\nSTATED AGE\n18 years old\nCASKTYPE\nBourbon, Sherry\nSTRENGTH\n43.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "18 years old",
					"casktype": "Bourbon, Sherry",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010496001400"
				},
				{
					"code": "Bowmore 21-year-old",
					"shortname": "Bowmore 21-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBowmore\nBOTTLER\nDistillery Bottling\nBOTTLING SERIE\nwhite stripe on capsule\nBOTTLED\n2003\nSTATED AGE\n21 years old\nSTRENGTH\n43.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Bowmore",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "21 years old",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496120828"
				},
				{
					"code": "Bruichladdich The Classic Laddie",
					"shortname": "Bruichladdich The Classic Laddie",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nBruichladdich\nBottler\nDistillery Bottling\nBottling serie\nThe Classic Laddie\nBottled\n2013\nStrength\n50.0 % Vol.\nSize\n700 ml 700 ml 750 ml\nBottle code\nP/131056 13/148 21 JUN 13\nBarcode\n0518105003159",
					"category": "Single Malt",
					"distillerycodes": "Bruichladdich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "50.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "0518105003159"
				},
				{
					"code": "Bruichladdich First Edition Miniature Tasting Pack",
					"shortname": "Bruichladdich First Edition Miniature Tasting Pack",
					"region": "Islay",
					"description": "",
					"category": "Single Malt",
					"distillerycodes": "Bruichladdich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "",
					"size": "",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "618105705524"
				},
				{
					"code": "Bunnahabhain Moine",
					"shortname": "Bunnahabhain Moine",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBunnahabhain\nBOTTLER\nDistillery Bottling\nBOTTLED\n2015\nSTATED AGE\n06 years old\nSTRENGTH\n46.3 % Vol.\nSIZE\n700 ml\nBOTTLE CODE\n-\nBARCODE\n5029704218141",
					"category": "Single Malt",
					"distillerycodes": "Bunnahabhain",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "06 years old",
					"casktype": "",
					"strength": "46.3 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5029704218141"
				},
				{
					"code": "Bunnahabhain 11-year-old",
					"shortname": "Bunnahabhain 11-year-old",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nBunnahabhain\nBottler\nGordon & MacPhail (GM)\nBottling serie\nDiscovery\nBottled\n2018\nStated Age\n11 years old\nCasktype\nSherry Cask\nStrength\n43.0 % Vol.\nSize\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Bunnahabhain",
					"bottlercodes": "Gordon & MacPhail (GM)",
					"brandcodes": "",
					"statedage": "11 years old",
					"casktype": "Sherry Cask",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": ""
				},
				{
					"code": "Bunnahabhain 12-year-old",
					"shortname": "Bunnahabhain 12-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBunnahabhain\nBOTTLER\nDistillery Bottling\nBOTTLED\n2012\nSTATED AGE\n12 years old\nSTRENGTH\n46.3 % Vol.\nSIZE\n700 ml\nBOTTLE CODE\nP0 29224 L5\nBARCODE\n5029704217366",
					"category": "Single Malt",
					"distillerycodes": "Bunnahabhain",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "12 years old",
					"casktype": "",
					"strength": "46.3 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5029704217366"
				},
				{
					"code": "Bunnahabhain-18-year-old",
					"shortname": "Bunnahabhain-18-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBunnahabhain\nBOTTLER\nDistillery Bottling\nSTATED AGE\n18 years old\nSTRENGTH\n46.3 % Vol.\nSIZE\n700 ml\nBOTTLE CODE\n-\nBARCODE\n5029704217373",
					"category": "Single Malt",
					"distillerycodes": "Bunnahabhain",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "18 years old",
					"casktype": "",
					"strength": "46.3 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5029704217373"
				},
				{
					"code": "Bunnahabhain Eirigh Na Greine",
					"shortname": "Bunnahabhain Eirigh Na Greine",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nBunnahabhain\nBOTTLER\nDistillery Bottling\nBOTTLING SERIE\nLimited Edition Release\nBOTTLED\n2017\nCASKTYPE\nItalian & French Red Wine Casks\nSTRENGTH\n46.3 % Vol.\nSIZE\n1000 ml\nBOTTLED FOR\nTravel Retail",
					"category": "Single Malt",
					"distillerycodes": "Bunnahabhain",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Italian & French Red Wine Casks",
					"strength": "46.3 % Vol.",
					"size": "1000 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5029704217793"
				},
				{
					"code": "Caol Ila 12-year-old",
					"shortname": "Caol Ila 12-year-old",
					"region": "Islay",
					"description": "Category: Single Malt \nBottled: - \nStated age: 12 years old \nCasktype:  \nStrength: 43.0 % Vol. \nSize: 700 ml",
					"category": "Single Malt",
					"distillerycodes": "CaolIla",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5000281016290"
				},
				{
					"code": "Caol Ila 13-year-old",
					"shortname": "Caol Ila 13-year-old",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nCaol Ila\nBottler\nGordon & MacPhail (GM)\nBottling serie\nDiscovery\nBottled\n18.04.2018\nStated Age\n13 years old\nCasktype\nBourbon\nStrength\n43.0 % Vol.\nSize\n700 ml\nBottle code\n18/04/18 180491\nBarcode\n5020613067660",
					"category": "Single Malt",
					"distillerycodes": "CaolIla",
					"bottlercodes": "Gordon & MacPhail (GM)",
					"brandcodes": "",
					"statedage": "13 years old",
					"casktype": "Bourbon",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5020613067660"
				},
				{
					"code": "Caol Ila cask strength 1991",
					"shortname": "Caol Ila cask strength 1991",
					"region": "Islay",
					"description": "Category: Single Malt \nBottling Serie: The Ultimage\nVintage: 13.08.1991\nBottled: 05.02.2001\nStated age: 9 years old \nCasknumber: 10782 \nStrength: 59.0 % Vol. \nSize: 700 m",
					"category": "Single Malt",
					"distillerycodes": "CaolIla",
					"bottlercodes": "van Wees (vW)",
					"brandcodes": "",
					"statedage": "09 years old",
					"casktype": "",
					"strength": "59.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": ""
				},
				{
					"code": "Connemara Original",
					"shortname": "Connemara Original",
					"region": "Ireland",
					"description": "Category\nSingle Malt\nDistillery\nCooley Distillery\nBottler\nDistillery Bottling\nBottled\n07.03.2017\nStrength\n40.0 % Vol.\nSize\n700 ml\nLabel\npeated single malt Irish whisky\nBottle code\nL17031\nBarcode\n5099357002305",
					"category": "Single Malt",
					"distillerycodes": "Cooley",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5099357002305"
				},
				{
					"code": "Finlaggan old reserve",
					"shortname": "Finlaggan old reserve",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Vintage Malt Whisky Co Ltd. (VM)\nBottled\n02.04.2015\nStrength\n40.0 % Vol.\nSize\n700 ml\nLabel\nCork Stopper\nBottle code\nL 02 04 15\nBarcode\n5024720900001",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Vintage Malt Whisky Co Ltd. (VM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5024720900001"
				},
				{
					"code": "Finlaggan Original",
					"shortname": "Finlaggan Original",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Vintage Malt Whisky Co Ltd. (VM)\nBottled\n07.09.2015\nStrength\n40.0 % Vol.\nSize\n700 ml\nBarcode\n5024720350004",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Vintage Malt Whisky Co Ltd. (VM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5024720350004"
				},
				{
					"code": "Finlaggan Cask Strength",
					"shortname": "Finlaggan Cask Strength",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Vintage Malt Whisky Co Ltd. (VM)\nBottled\n2013\nStrength\n58.0 % Vol.\nSize\n700 ml\nLabel\nNew Label, Green Bottle\nBarcode\n5024720460000",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Vintage Malt Whisky Co Ltd. (VM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "58.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5024720460000"
				},
				{
					"code": "Finlaggan Port Finish VM",
					"shortname": "Finlaggan Port Finish VM",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Vintage Malt Whisky Co Ltd. (VM)\nBottled\n2016\nCasktype\nEx-Bourbon & Port Cask Finish\nStrength\n46.0 % Vol.\nSize\n700 ml\nBarcode\n5024720313009",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Vintage Malt Whisky Co Ltd. (VM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Ex-Bourbon & Port Cask Finish",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5024720313009"
				},
				{
					"code": "Finlaggan Sherry Finish VM",
					"shortname": "Finlaggan Sherry Finish VM",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Vintage Malt Whisky Co Ltd. (VM)\nBottled\n2016\nCasktype\nEx-Bourbon & Sherry Cask Finish\nNumber of bottles\n3000\nStrength\n46.0 % Vol.\nSize\n700 ml\nBarcode\n5024720315003",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Vintage Malt Whisky Co Ltd. (VM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Ex-Bourbon & Sherry Cask Finish",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5024720315003"
				},
				{
					"code": "Frysk Hynder",
					"shortname": "Frysk Hynder",
					"region": "Netherlands",
					"description": "Category\nSingle Malt\nDistillery\nUs Heit Distillery\nBottler\nDistillery Bottling\nVintage\n29.01.2009\nBottled\n31.05.2012\nStated Age\n03 years old\nCasktype\nRed Wine Cask\nCasknumber\n113\nStrength\n40.0 % Vol.\nSize\n700 ml\nBarcode\n8713615006856",
					"category": "Single Malt",
					"distillerycodes": "UsHeit",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "03 years old",
					"casktype": "Red Wine Cask",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "8713615006856"
				},
				{
					"code": "Glenfiddich XX",
					"shortname": "Glenfiddich XX",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenfiddich\nBottler\nDistillery Bottling\nBottling serie\nExperimental Series No. 02\nBottled\n2016\nStrength\n47.0 % Vol.\nSize\n700 ml 750 ml\nBottle code\nL34A49290512134445\nBarcode\n5010327325613",
					"category": "Single Malt",
					"distillerycodes": "Glenfiddich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "47.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010327325613"
				},
				{
					"code": "Glenfiddich 12-year-old",
					"shortname": "Glenfiddich 12-year-old",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenfiddich\nBottler\nDistillery Bottling\nStated Age\n12 years old\nCasktype\nOloroso Sherry & Bourbon Casks\nStrength\n40.0 % Vol.\nSize\n700 ml\nBottle code\nL2W778411121534\nBarcode\n5010327000176",
					"category": "Single Malt",
					"distillerycodes": "Glenfiddich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "12 years old",
					"casktype": "Oloroso Sherry & Bourbon Casks",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010327000176"
				},
				{
					"code": "Glenfiddich IPA experiment",
					"shortname": "Glenfiddich IPA experiment",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenfiddich\nBottler\nDistillery Bottling\nBottling serie\nExperimental Series No. 01\nBottled\n2016\nCasktype\nIndia Pale Ale Cask Finish\nStrength\n43.0 % Vol.\nSize\n700 ml 700 ml\nBarcode\n5010327325606",
					"category": "Single Malt",
					"distillerycodes": "Glenfiddich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "India Pale Ale Cask Finish",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010327325606"
				},
				{
					"code": "Glenfiddich Single Malt Collection (3x20cl)",
					"shortname": "Glenfiddich Single Malt Collection (3x20cl)",
					"region": "Speyside",
					"description": "",
					"category": "Single Malt",
					"distillerycodes": "Glenfiddich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "12, 15, 18 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "200 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010327098104"
				},
				{
					"code": "Glenfiddich 14-year-old Rich Oak",
					"shortname": "Glenfiddich 14-year-old Rich Oak",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenfiddich\nBottler\nDistillery Bottling\nBottling serie\nRich Oak\nBottled\n16.10.2014\nStated Age\n14 years old\nCasktype\nNew American & European Oak Casks\nStrength\n40.0 % Vol.\nSize\n700 ml\nBottle code\nL32Y 4849 1610 1048\nBarcode\n5010327325170",
					"category": "Single Malt",
					"distillerycodes": "Glenfiddich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "14 years old",
					"casktype": "New American & European Oak Casks",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010327325170"
				},
				{
					"code": "Glenfiddich 15-year-old",
					"shortname": "Glenfiddich 15-year-old",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenfiddich\nBottler\nDistillery Bottling\nBottling serie\nUnique Solera Reserve\nBottled\n2015\nStated Age\n15 years old\nStrength\n40.0 % Vol.\nSize\n200 ml 700 ml\nBarcode\n5010327325125",
					"category": "Single Malt",
					"distillerycodes": "Glenfiddich",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "15 years old",
					"casktype": "Sherry, Bourbon, and New Oak",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010327325125"
				},
				{
					"code": "Glengoyne 12-year-old SingleCask",
					"shortname": "Glengoyne 12-year-old SingleCask",
					"region": "Highland",
					"description": "Category\nSingle Malt\nDistillery\nGlengoyne\nBottler\nDistillery Bottling\nBottling serie\nSingle Cask\nVintage\n10.1994\nBottled\n11.2006\nStated Age\n12 years old\nCasktype\nMuscatel Finish\nCasknumber\n90163\nNumber of bottles\n342\nStrength\n43.0 % Vol.\nSize\n700 ml\nBarcode\n5010852013290",
					"category": "Single Malt",
					"distillerycodes": "Glengoyne",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "12 years old",
					"casktype": "Muscatel Finish",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010852013290"
				},
				{
					"code": "Glenlivet 12-year-old",
					"shortname": "Glenlivet 12-year-old",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenlivet\nBottler\nDistillery Bottling\nBottled\n2006\nStated Age\n12 years old\nStrength\n40.0 % Vol.\nSize\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Glenlivet",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "12 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "2",
					"collectionopen": "",
					"barcode": "080432402825"
				},
				{
					"code": "Glenlivet 18-year-old",
					"shortname": "Glenlivet 18-year-old",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nGlenlivet\nBottler\nDistillery Bottling\nBottled\n28.11.2017\nStated Age\n18 years old\nStrength\n43.0 % Vol.\nSize\n700 ml\nBottle code\nLKPL4894\nBarcode\n080432403105",
					"category": "Single Malt",
					"distillerycodes": "Glenlivet",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "18 years old",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "080432403105"
				},
				{
					"code": "ILeach",
					"shortname": "ILeach",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Highlands & Islands (H&I)\nStrength\n40.0 % Vol.\nSize\n700 ml\nLabel\nNew Label\nBarcode\n5024720700007",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Highlands & Islands (H&I)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5024720700007"
				},
				{
					"code": "Ileach Cask Strength",
					"shortname": "Ileach Cask Strength",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nThe Highlands & Islands (H&I)\nBottling serie\nCask Strength\nBottled\n04.04.2016\nStrength\n58.0 % Vol.\nSize\n700 ml\nBottle code\nL 04 04 16\nBarcode\n5024720500508",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "The Highlands & Islands (H&I)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "58.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5024720500508"
				},
				{
					"code": "Isle of Jura 10-year-old",
					"shortname": "Isle of Jura 10-year-old",
					"region": "Island",
					"description": "Category\nSingle Malt\nDistillery\nIsle of Jura\nBottler\nDistillery Bottling\nBottling serie\nOrigin\nBottled\n2014\nStated Age\n10 years old\nStrength\n40.0 % Vol.\nSize\n700 ml\nBottle code\nL4281 01:19 14/02928\nBarcode\n5014366080946",
					"category": "Single Malt",
					"distillerycodes": "Jura",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5014366080946"
				},
				{
					"code": "Isle of Jura Superstition",
					"shortname": "Isle of Jura Superstition",
					"region": "Island",
					"description": "Category\nSingle Malt\nDistillery\nIsle of Jura\nBottler\nDistillery Bottling\nBottled\n30.06.2017\nStrength\n43.0 % Vol.\nSize\n700 ml\nBottle code\nL7181P/002003\nBarcode\n5013967002821",
					"category": "Single Malt",
					"distillerycodes": "Jura",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5013967002821"
				},
				{
					"code": "Kilchoman 2018 Loch Gorm",
					"shortname": "Kilchoman 2018 Loch Gorm",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nKilchoman\nBottler\nDistillery Bottling\nBottling serie\n6th Edition\nVintage\n2007, 2008, 2011\nBottled\nSpring 2018\nCasktype\n19 Oloroso Sherry Butts\nNumber of bottles\n15000\nStrength\n46.0 % Vol.\nSize\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Kilchoman",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "19 Oloroso Sherry Butts",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5060210701543"
				},
				{
					"code": "Kilchoman Sanaig",
					"shortname": "Kilchoman Sanaig",
					"region": "Islay",
					"description": "Category: Single Malt \nBottled: - \nStated age: - \nCasktype: Bourbon & Sherry Casks \nStrength: 46.0 % Vol. \nSize: 700 ml",
					"category": "Single Malt",
					"distillerycodes": "Kilchoman",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Bourbon & Sherry Casks",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5060210700607"
				},
				{
					"code": "Kilchoman 2010 Summer",
					"shortname": "Kilchoman 2010 Summer",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nKilchoman\nBOTTLER\nDistillery Bottling\nVINTAGE\n2007\nBOTTLED\n2010\nSTATED AGE\n03 years old\nCASKTYPE\nFresh and Refill Bourbon Barrels\nNUMBER OF BOTTLES\n17500\nSTRENGTH\n46.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Kilchoman",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "03 years old",
					"casktype": "Fresh and Refill Bourbon Barrels",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5060210700072"
				},
				{
					"code": "Kilchoman Machir Bay",
					"shortname": "Kilchoman Machir Bay",
					"region": "Islay",
					"description": "",
					"category": "",
					"distillerycodes": "",
					"bottlercodes": "",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "",
					"size": "",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5060210700522"
				},
				{
					"code": "Lagavulin 1999 Destiller Edition 16-year-old",
					"shortname": "Lagavulin 1999 Destiller Edition 16-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nLagavulin\nBOTTLER\nDistillery Bottling\nBOTTLING SERIE\nThe Distillers Edition\nVINTAGE\n1999\nBOTTLED\n2015\nCALCULATED AGE\n16 years old\nCASKTYPE\nDouble Matured in Pedro Ximénez Sherry Casks\nSTRENGTH\n43.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Lagavulin",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "16 years old",
					"casktype": "Double Matured in Pedro Ximénez Sherry Casks",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5000281013480"
				},
				{
					"code": "Lagavulin 16-year-old",
					"shortname": "Lagavulin 16-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nLagavulin\nBOTTLER\nDistillery Bottling\nSTATED AGE\n16 years old\nSTRENGTH\n43.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Lagavulin",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "16 years old",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5000281005409"
				},
				{
					"code": "Lagavulin 1987",
					"shortname": "Lagavulin 1987",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nLagavulin\nBOTTLER\nDistillery Bottling\nBOTTLING SERIE\nThe Distillers Edition\nVINTAGE\n1987\nBOTTLED\n2003\nCASKTYPE\nDouble matured in Pedro Ximenez Sherry Wood\nSTRENGTH\n43.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Lagavulin",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Double matured in Pedro Ximenez Sherry Wood",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5000281013480"
				},
				{
					"code": "Lagavulin 8-year-old",
					"shortname": "Lagavulin 8-year-old",
					"region": "Islay",
					"description": "CATEGORY\nSingle Malt\nDISTILLERY\nLagavulin\nBOTTLER\nDistillery Bottling\nBOTTLING SERIE\nLimited Edition - 200th Anniversary\nBOTTLED\n2016\nSTATED AGE\n08 years old\nCASKTYPE\nRefill American Oak Casks\nNUMBER OF BOTTLES\n20000\nSTRENGTH\n48.0 % Vol.\nSIZE\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Lagavulin",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "08 years old",
					"casktype": "Refill American Oak Casks",
					"strength": "48.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5000281045146"
				},
				{
					"code": "Laphroaig 10-year-old",
					"shortname": "Laphroaig 10-year-old",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nLaphroaig\nBottler\nDistillery Bottling\nBottled\n2013\nStated Age\n10 years old\nStrength\n40.0 % Vol.\nSize\n700 ml\nLabel\nNew Label\nBottle code\nL334557A\nBarcode\n5010019640260",
					"category": "Single Malt",
					"distillerycodes": "Laphroaig",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010019640260"
				},
				{
					"code": "Laphroaig QA Cask",
					"shortname": "Laphroaig QA Cask",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nLaphroaig\nBottler\nDistillery Bottling\nBottling serie\nTravel Retail Exclusive\nBottled\n2013\nCasktype\nex-Bourbon & un-charred American oak barrels\nStrength\n40.0 % Vol.\nSize\n1000 ml\nBarcode\n5010019637406",
					"category": "Single Malt",
					"distillerycodes": "Laphroaig",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "ex-Bourbon & un-charred American oak barrels",
					"strength": "40.0 % Vol.",
					"size": "1000 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010019637406"
				},
				{
					"code": "Macallan Amber",
					"shortname": "Macallan Amber",
					"region": "Speyside",
					"description": "",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "",
					"size": "",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": ""
				},
				{
					"code": "Double Barrel Macallan / Laphroaig DL",
					"shortname": "Double Barrel Macallan / Laphroaig DL",
					"region": "Blended Malt",
					"description": "Category\nBlended Malt\nDistilleries\nLaphroaig, Macallan\nBottler\nDouglas Laing (DL)\nBottled\n2009\nStated Age\n08 years old\nStrength\n46.0 % Vol.\nSize\n700 ml 750 ml\nBarcode\n5014218775389",
					"category": "Blended Malt",
					"distillerycodes": "Laphroaig, Macallan",
					"bottlercodes": "Douglas Laing (DL)",
					"brandcodes": "",
					"statedage": "08 years old",
					"casktype": "",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": ""
				},
				{
					"code": "Macallan Select Oak",
					"shortname": "Macallan Select Oak",
					"region": "Speyside",
					"description": "Category\nSingle Malt\nDistillery\nMacallan\nBottler\nDistillery Bottling\nBottling serie\nThe 1824 Collection\nBottled\n2012\nCasktype\nSherry & Bourbon Casks\nStrength\n40.0 % Vol.\nSize\n1000 ml\nBottle code\nL0453S L2 12/11 11:24\nBarcode\n5010314078003\nBottled for\nTravel Retail",
					"category": "Single Malt",
					"distillerycodes": "Macallan",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Sherry & Bourbon Casks",
					"strength": "40.0 % Vol.",
					"size": "1000 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010314078003"
				},
				{
					"code": "Majesty Islay",
					"shortname": "Majesty Islay",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nHighland Queen Scotch Whisky Company (HQSW)\nBottling serie\nMajesty - Islay Single Malt\nCasktype\nOak Casks\nStrength\n40.0 % Vol.\nSize\n700 ml\nBarcode\n5060074862053\nBottled for\nGall & Gall",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "Highland Queen Scotch Whisky Company (HQSW)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "Oak Casks",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5060074862053"
				},
				{
					"code": "Mc Lelland's Port Charlotte",
					"shortname": "Mc Lelland's Port Charlotte",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nT. & A. McClelland Ltd. (TAMC)\nBottling serie\nSingle Malt Scotch Whisky\nStrength\n40.0 % Vol.\nSize\n700 ml\nLabel\nBlack '1818'\nBottle code\nL122098 093 13:44\nBarcode\n5010496530818",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "T. & A. McClelland Ltd. (TAMC)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010496530818"
				},
				{
					"code": "Oban 14-year-old",
					"shortname": "Oban 14-year-old",
					"region": "Highland",
					"description": "Category\nSingle Malt\nDistillery\nOban\nBottler\nDistillery Bottling\nBottled\n13.10.2015\nStated Age\n14 years old\nStrength\n43.0 % Vol.\nSize\n700 ml\nBottle code\nL5 286 CM000\nBarcode\n5000281005447",
					"category": "Single Malt",
					"distillerycodes": "Oban",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "14 years old",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "2",
					"collectionopen": "",
					"barcode": "5000281005447"
				},
				{
					"code": "Peatmonster",
					"shortname": "Peatmonster",
					"region": "Blended Malt",
					"description": "Category\nBlended Malt\nDistilleries\nCaol Ila, Laphroaig, Clynelish, Teaninich, Ardmore, Tobermory, Dailuaine\nBottler\nCompass Box (CB)\nStrength\n46.0 % Vol.\nSize\n700 ml\nBottle code\nL 18 01 16 11:22 BB\nBarcode\n5065000482190",
					"category": "Blended Malt",
					"distillerycodes": "CaolIla, Laphroaig, Clynelish, Teaninich, Ardmore, Tobermory, Dailuaine",
					"bottlercodes": "Compass Box (CB)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5065000482190"
				},
				{
					"code": "Port Askaig",
					"shortname": "Port Askaig",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nSpeciality Drinks Ltd (SMS)\nBottled\n2016\nStated Age\n08 years old\nStrength\n45.8 % Vol.\nSize\n700 ml\nBottle code\nL16/8629",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "Speciality Drinks Ltd (SMS)",
					"brandcodes": "",
					"statedage": "08 years old",
					"casktype": "",
					"strength": "45.8 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5060188982098"
				},
				{
					"code": "Port Ellen 1979 22-year-old",
					"shortname": "Port Ellen 1979 22-year-old",
					"region": "Islay",
					"description": "Category\nSingle Malt\nDistillery\nPort Ellen\nBottler\nSignatory Vintage (SV)\nBottling serie\nVintage Collection\nVintage\n09.08.1979\nBottled\n18.02.2002\nStated Age\n22 years old\nCasktype\nOak Cask\nCasknumber\n5145\nNumber of bottles\n345\nStrength\n43.0 % Vol.\nSize\n700 ml\nBottle code\n02/0181",
					"category": "Single Malt",
					"distillerycodes": "PortEllen",
					"bottlercodes": "Signatory Vintage (SV)",
					"brandcodes": "",
					"statedage": "22 years old",
					"casktype": "Oak Cask",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": ""
				},
				{
					"code": "Scapa 14-year-old",
					"shortname": "Scapa 14-year-old",
					"region": "Island",
					"description": "Category\nSingle Malt\nDistillery\nScapa\nBottler\nDistillery Bottling\nBottled\n2007\nStated Age\n14 years old\nStrength\n40.0 % Vol.\nSize\n700 ml 750 ml 1000 ml\nBarcode\n5010106172995",
					"category": "Single Malt",
					"distillerycodes": "Scapa",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "14 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010106172995"
				},
				{
					"code": "The Six Isles",
					"shortname": "The Six Isles",
					"region": "Blended Malt",
					"description": "Category\nBlended Malt\nBottler\nIan Macleod (IM)\nBottling serie\nBlended Malt Scotch Whisky\nStrength\n43.0 % Vol.\nSize\n700 ml\nLabel\nNew Bottle Design (2011)\nBarcode\n5010852005950",
					"category": "Blended Malt",
					"distillerycodes": "",
					"bottlercodes": "Ian Macleod (IM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5010852005950"
				},
				{
					"code": "Smokehead",
					"shortname": "Smokehead",
					"region": "Islay",
					"description": "Category\nSingle Malt\nBottler\nIan Macleod (IM)\nBottled\n11.04.2016\nStrength\n43.0 % Vol.\nSize\n700 ml\nBottle code\nL 11 04 16 3 06:58 BB\nBarcode\n5010852010701",
					"category": "Single Malt",
					"distillerycodes": "",
					"bottlercodes": "Ian Macleod (IM)",
					"brandcodes": "",
					"statedage": "",
					"casktype": "",
					"strength": "43.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5010852010701"
				},
				{
					"code": "Springbank",
					"shortname": "Springbank",
					"region": "Campbeltown",
					"description": "Category\nSingle Malt\nDistillery\nSpringbank\nBottler\nDistillery Bottling\nBottled\n2016\nStated Age\n10 years old\nStrength\n46.0 % Vol.\nSize\n700 ml\nBottle code\n16/474\nBarcode\n61085410700",
					"category": "Single Malt",
					"distillerycodes": "Springbank",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "46.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "61085410700"
				},
				{
					"code": "Talisker 10-year-old",
					"shortname": "Talisker 10-year-old",
					"region": "Island",
					"description": "Category\nSingle Malt\nDistillery\nTalisker\nBottler\nDistillery Bottling\nBottled\n10.09.2013\nStated Age\n10 years old\nStrength\n45.8 % Vol.\nSize\n700 ml\nLabel\nNew Map Label\nBottle code\nL3252CM000\nBarcode\n5000281005416",
					"category": "Single Malt",
					"distillerycodes": "Talisker",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "45.8 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "5000281005416"
				},
				{
					"code": "Tobermory 10-year-old",
					"shortname": "Tobermory 10-year-old",
					"region": "Island",
					"description": "Category\nSingle Malt\nDistillery\nTobermory\nBottler\nDistillery Bottling\nBottled\n2002\nStated Age\n10 years old\nStrength\n40.0 % Vol.\nSize\n700 ml 700 ml\nLabel\nGlass print label\nBottle code\n5319 12:50 L16 P005316\nBarcode\n5013261140595",
					"category": "Single Malt",
					"distillerycodes": "Tobermory",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "10 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "",
					"collectionopen": "",
					"barcode": "5013261140595"
				},
				{
					"code": "Wambrechies",
					"shortname": "Wambrechies",
					"region": "France",
					"description": "Category\nSingle Malt\nDistillery\nDistillerie Claeyssens de Wambrechies\nBottler\nDistillery Bottling\nStated Age\n03 years old\nStrength\n40.0 % Vol.\nSize\n700 ml",
					"category": "Single Malt",
					"distillerycodes": "Wambrechies",
					"bottlercodes": "Distillery Bottling",
					"brandcodes": "",
					"statedage": "03 years old",
					"casktype": "",
					"strength": "40.0 % Vol.",
					"size": "700 ml",
					"collectionclosed": "1",
					"collectionopen": "",
					"barcode": "3263592308535"
				}
			]
		},
		"files": {
			"file": [
				{
					"filename": "Arbeg-Blasda",
					"unc": "/BottlingPhotos/Arbeg-Blasda.jpg",
					"bottlingcodes": "Ardbeg Blasda",
					"distillerycodes": ""
				},
				{
					"filename": "Arbeg-Uigeadail",
					"unc": "/BottlingPhotos/Arbeg-Uigeadail.jpg",
					"bottlingcodes": "Ardbeg Uigeadail",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-10",
					"unc": "/BottlingPhotos/Ardbeg-10.jpg",
					"bottlingcodes": "Ardbeg Ten",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-10-17-mini",
					"unc": "/BottlingPhotos/Ardbeg-10-17-mini.jpg",
					"bottlingcodes": "Ardbeg 10 and 17 Year Old Presentation Tin",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-17",
					"unc": "/BottlingPhotos/Ardbeg-17.jpg",
					"bottlingcodes": "Ardbeg 17-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-18",
					"unc": "/BottlingPhotos/Ardbeg-18.jpg",
					"bottlingcodes": "Ardbeg 18-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-Alligator",
					"unc": "/BottlingPhotos/Ardbeg-Alligator.jpg",
					"bottlingcodes": "Ardbeg Alligator",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-Corryvreckan",
					"unc": "/BottlingPhotos/Ardbeg-Corryvreckan.jpg",
					"bottlingcodes": "Ardbeg Corryvreckan",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-Darkcove",
					"unc": "/BottlingPhotos/Ardbeg-Darkcove.jpg",
					"bottlingcodes": "Ardbeg Dark Cove",
					"distillerycodes": ""
				},
				{
					"filename": "Ardbeg-Renaissance",
					"unc": "/BottlingPhotos/Ardbeg-Renaissance.jpg",
					"bottlingcodes": "Ardbeg Renaissance",
					"distillerycodes": ""
				},
				{
					"filename": "Arran-10",
					"unc": "/BottlingPhotos/Arran-10.jpg",
					"bottlingcodes": "Arran 10-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "MacallanLaphroaig",
					"unc": "/BottlingPhotos/MacallanLaphroaig.JPG",
					"bottlingcodes": "Double Barrel Macallan / Laphroaig DL",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore 9-years-old",
					"unc": "/BottlingPhotos/Bowmore 9-years-old.jpg",
					"bottlingcodes": "Bowmore 09-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore No 1",
					"unc": "/BottlingPhotos/Bowmore No 1.jpg",
					"bottlingcodes": "Bowmore No. 1",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore-12",
					"unc": "/BottlingPhotos/Bowmore-12.jpg",
					"bottlingcodes": "Bowmore 12-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore-15",
					"unc": "/BottlingPhotos/Bowmore-15.jpg",
					"bottlingcodes": "Bowmore 15-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "bowmore-18-years",
					"unc": "/BottlingPhotos/bowmore-18-years.jpg",
					"bottlingcodes": "Bowmore 18-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore-21",
					"unc": "/BottlingPhotos/Bowmore-21.jpg",
					"bottlingcodes": "Bowmore 21-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore-8",
					"unc": "/BottlingPhotos/Bowmore-8.jpg",
					"bottlingcodes": "Bowmore 08-year-old",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore-Legend",
					"unc": "/BottlingPhotos/Bowmore-Legend.jpg",
					"bottlingcodes": "Bowmore Legend",
					"distillerycodes": ""
				},
				{
					"filename": "Bowmore-Whitesands",
					"unc": "/BottlingPhotos/Bowmore-Whitesands.jpg",
					"bottlingcodes": "Bowmore 17-year-old Whitesands",
					"distillerycodes": ""
				},
				{
					"filename": "BruichladdichClassic",
					"unc": "/Bottle%20Photos/Bruichladdich/BruichladdichClassic.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "BruichladdichMini",
					"unc": "/Bottle%20Photos/Bruichladdich/BruichladdichMini.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Bunnahabhain Moine",
					"unc": "/Bottle%20Photos/Bunnahabhain/Bunnahabhain Moine.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Bunnahabhain-12",
					"unc": "/Bottle%20Photos/Bunnahabhain/Bunnahabhain-12.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Bunnahabhain-18",
					"unc": "/Bottle%20Photos/Bunnahabhain/Bunnahabhain-18.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Bunnahabhain-EirighNaGreine",
					"unc": "/Bottle%20Photos/Bunnahabhain/Bunnahabhain-EirighNaGreine.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "CaolIla12",
					"unc": "/Bottle%20Photos/CaolIla/CaolIla12.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "CaolIla-13-years-old",
					"unc": "/Bottle%20Photos/CaolIla/CaolIla-13-years-old.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "CaolIla1991",
					"unc": "/Bottle%20Photos/CaolIla/CaolIla1991.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "connemara",
					"unc": "/Bottle%20Photos/Connemara/connemara.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "MacallanLaphroaig",
					"unc": "/Bottle%20Photos/Douglas Laing (DL)/MacallanLaphroaig.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Lagavulin-16",
					"unc": "/Bottle%20Photos/Lagavulin/Lagavulin-16.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Lagavulin-8",
					"unc": "/Bottle%20Photos/Lagavulin/Lagavulin-8.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Laphroaig-10",
					"unc": "/Bottle%20Photos/Laphroaig/Laphroaig-10.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "laphroaig-qa",
					"unc": "/Bottle%20Photos/Laphroaig/laphroaig-qa.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Majesty",
					"unc": "/Bottle%20Photos/Majesty/Majesty.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "IMG_0075",
					"unc": "/Bottle%20Photos/Oban/IMG_0075.JPG",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "PortEllen-22-SingleCask",
					"unc": "/Bottle%20Photos/PortEllen/PortEllen-22-SingleCask.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Wambrechies",
					"unc": "/Bottle%20Photos/Wambrechies/Wambrechies.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "ardbeg",
					"unc": "/Brand%20Logos/ardbeg.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "douglas-laing",
					"unc": "/Brand%20Logos/douglas-laing.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "ardbeg-panorama",
					"unc": "/DistilleryPhotos/ardbeg-panorama.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Ardbeg"
				},
				{
					"filename": "arran_distillery",
					"unc": "/DistilleryPhotos/arran_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Arran"
				},
				{
					"filename": "bowmore-distillery",
					"unc": "/DistilleryPhotos/bowmore-distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Bowmore"
				},
				{
					"filename": "bruichladdich_distillery",
					"unc": "/DistilleryPhotos/bruichladdich_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Bruichladdich"
				},
				{
					"filename": "bunnahabhain_distillery",
					"unc": "/DistilleryPhotos/bunnahabhain_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Bunnahabhain"
				},
				{
					"filename": "caol_ila_distillery",
					"unc": "/DistilleryPhotos/caol_ila_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "CaolIla"
				},
				{
					"filename": "cragganmore_distillery",
					"unc": "/DistilleryPhotos/cragganmore_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "glenfiddich-distillery",
					"unc": "/DistilleryPhotos/glenfiddich-distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Glenfiddich"
				},
				{
					"filename": "glenlivet-distillery",
					"unc": "/DistilleryPhotos/glenlivet-distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Glenlivet"
				},
				{
					"filename": "IsleOfJura_Distillery",
					"unc": "/DistilleryPhotos/IsleOfJura_Distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Jura"
				},
				{
					"filename": "kilbeggandistillery",
					"unc": "/DistilleryPhotos/kilbeggandistillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": ""
				},
				{
					"filename": "Kilchoman_Distillery",
					"unc": "/DistilleryPhotos/Kilchoman_Distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Kilchoman"
				},
				{
					"filename": "lagavulin-distillery",
					"unc": "/DistilleryPhotos/lagavulin-distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Lagavulin"
				},
				{
					"filename": "laphroaig_distillery",
					"unc": "/DistilleryPhotos/laphroaig_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Laphroaig"
				},
				{
					"filename": "macallan_distillery",
					"unc": "/DistilleryPhotos/macallan_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Macallan"
				},
				{
					"filename": "oban_distillery",
					"unc": "/DistilleryPhotos/oban_distillery.JPG",
					"bottlingcodes": "",
					"distillerycodes": "Oban"
				},
				{
					"filename": "portellen_distillery",
					"unc": "/DistilleryPhotos/portellen_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "PortEllen"
				},
				{
					"filename": "scapa_distillery",
					"unc": "/DistilleryPhotos/scapa_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Scapa"
				},
				{
					"filename": "springbank_distillery",
					"unc": "/DistilleryPhotos/springbank_distillery.jpg",
					"bottlingcodes": "",
					"distillerycodes": "Springbank"
				},
				{
					"filename": "usheit",
					"unc": "/DistilleryPhotos/usheit.jpg",
					"bottlingcodes": "",
					"distillerycodes": "UsHeit"
				}
			]
		}
	}
};